name: Deploy Vue
on: [push]
jobs:
  build_vue:
    name: Build Vue
    runs-on: ubuntu-latest
    steps:
      uses: CultureHQ/actions-yarn@master
    - name: Install
      with:
        args: install

    - name: Build
      with:
        args: build

  push_vue:
    runs-on: ubuntu-latest
    name: Push Vue
    steps:
      run: |
            cd dist
            git config --global user.email "CI@example.com"
            git config --global user.name "vsme"
            git init
            git add -A
            git commit -m 'deploy'
            git push -f https://vsme:${{ secrets.GITHUB_TOKEN }}@github.com/vsme/vue-action-test.git master:gh-pages
      shell: bash