name: Deploy Vue
on: [push]
jobs:
  build_vue:
    name: Build Vue
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn build

  push_vue:
    runs-on: ubuntu-latest
    name: Push Vue
    steps:
    - run: cd dist
    - run: git config --global user.email "CI@example.com"
    - run: git config --global user.name "vsme"
    - run: git init
    - run: git add -A
    - run: git commit -m 'deploy'
    - run: git push -f https://vsme:${{ secrets.GITHUB_TOKEN }}@github.com/vsme/vue-action-test.git master:gh-pages
      shell: bash